# Dockerfile sécurisé

# Etape 1 : Builder
FROM golang:1.24-alpine AS builder
WORKDIR /src
COPY /app .
RUN CGO_ENABLED=0 go build -o /server

# Etape 2 : Runtime
FROM alpine:3.23
COPY --from=builder /server /server
USER timeo
ENTRYPOINT ["/serveur"]


